import { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'LORO CRM | #1 South African CRM for Field Sales, Lead Management & HR | Offline Capable',
    description:
        'Transform your business with LORO CRM - South Africa\'s leading offline-capable CRM system for field sales, quotation management, lead tracking, and HR attendance monitoring. Built for South African businesses with 24/7 local support. Works 100% offline with real-time GPS tracking for field workers. The most comprehensive CRM solution in Johannesburg, Cape Town, Durban, and all of South Africa.',
    keywords: [
        // Location-Specific
        'CRM South Africa',
        'CRM near me',
        'CRM Johannesburg',
        'CRM Cape Town',
        'CRM Durban',
        'CRM Pretoria',
        'CRM software South Africa',
        'sales CRM South Africa',
        'leads management South Africa',
        'field service software South Africa',
        'South African business software',
        'local CRM provider',

        // CRM Core
        'CRM',
        'customer relationship management',
        'client management system',
        'customer database',
        'contact management software',
        'customer tracking',
        'client interaction tracking',
        'customer segmentation',
        'customer journey mapping',
        'omnichannel CRM',
        'offline CRM',
        'CRM that works without internet',
        'best CRM for small business',
        'enterprise CRM solution',
        'affordable CRM',

        // Sales Management
        'sales pipeline',
        'lead management',
        'lead generation',
        'lead qualification',
        'sales automation',
        'sales forecasting',
        'opportunity management',
        'deal closing',
        'sales analytics',
        'revenue optimization',
        'quote management',
        'proposal automation',
        'sales territory management',
        'account-based selling',
        'upselling tools',
        'smart sales management',
        'sales performance tracking',
        'sales team management',
        'commission tracking',
        'smart quotation system',
        'quotation automation',
        'quotation templates',
        'quote approval workflow',
        'digital signatures for quotes',
        'online quotation system',

        // Lead Management
        'lead tracking software',
        'smart lead management',
        'lead scoring',
        'lead nurturing',
        'lead conversion analytics',
        'lead source tracking',
        'lead assignment',
        'automated lead distribution',
        'lead capture forms',
        'lead funnel analytics',
        'lead verification',
        'lead quality scoring',
        'lead lifecycle management',

        // Field Management & Monitoring
        'field service management',
        'field service automation',
        'field service software',
        'field workforce tracking',
        'mobile workforce management',
        'technician dispatching',
        'field employee monitoring',
        'GPS tracking system',
        'route optimization',
        'field data collection',
        'offline field operations',
        'mobile field reporting',
        'field service KPIs',
        'technician productivity',
        'service appointment scheduling',
        'offline GPS tracking',
        'field sales app',
        'door-to-door sales tracking',
        'field worker management',
        'remote team GPS',
        'GPS attendance verification',
        'location-based attendance',
        'geofence attendance',

        // Employee & HR Management
        'employee monitoring',
        'staff management system',
        'attendance tracking',
        'performance management',
        'HR analytics',
        'employee productivity tracking',
        'time tracking software',
        'workforce management',
        'staff scheduling',
        'employee reporting system',
        'team management solution',
        'remote worker monitoring',
        'employee task management',
        'staff training tracking',
        'talent management',
        'smart HR system',
        'smart attendance tracking',
        'biometric attendance alternative',
        'mobile attendance app',
        'HR compliance South Africa',
        'leave management',
        'employee onboarding',
        'HR document management',

        // Reporting & Analytics
        'business intelligence dashboard',
        'automated reporting',
        'real-time analytics',
        'performance metrics',
        'KPI tracking',
        'data visualization',
        'custom business reports',
        'executive dashboards',
        'operational insights',
        'business performance monitoring',
        'predictive analytics',
        'trend analysis',
        'reporting automation',
        'sales reporting',
        'lead analytics',
        'custom report builder',
        'scheduled reports',
        'data export',
        'real-time business metrics',
        'visual data representation',

        // Industry-Specific
        'field service CRM',
        'enterprise CRM solution',
        'SMB customer management',
        'industry-specific CRM',
        'scalable CRM platform',
        'inventory management CRM',
        'quotation management system',
        'claims management',
        'field service management software',
        'mobile CRM app',
        'CRM for construction',
        'CRM for manufacturing',
        'CRM for retail',
        'CRM for financial services',
        'CRM for healthcare',
        'CRM for real estate',
        'CRM for insurance',
        'CRM for logistics',

        // Technical Features
        'offline-capable CRM',
        'cloud-based CRM',
        'mobile CRM solution',
        'integrated business platform',
        'API-enabled CRM',
        'customizable CRM',
        'secure customer data platform',
        'multi-device CRM',
        'location-based services',
        'offline data synchronization',
        'low data usage app',
        'works in rural areas',
        'no internet required',
        'works during load shedding',
        'minimal data consumption',
    ],
    authors: [
        {
            name: 'Brandon Nhlanhla Nkawu',
            url: 'https://www.linkedin.com/in/brandonnkawu/',
        },
    ],
    openGraph: {
        title: 'LORO CRM | South Africa\'s #1 Offline-Capable CRM for Field Sales, Leads & HR',
        description:
            'South Africa\'s leading CRM platform with offline GPS tracking, smart lead management, quotation system, and field workforce monitoring. Perfect for businesses in Johannesburg, Cape Town, Durban and beyond, with 100% offline capability.',
        type: 'website',
        siteName: 'LORO CRM Platform',
        locale: 'en_ZA',
        images: [
            {
                url: 'https://storage.googleapis.com/crmapplications/resources/loro-og-image.jpg',
                width: 1200,
                height: 630,
                alt: 'LORO CRM Platform Dashboard showing field sales tracking and reporting',
            }
        ],
    },
    twitter: {
        card: 'summary_large_image',
        title: 'LORO CRM | South Africa\'s Leading Offline CRM for Field Sales & HR',
        description:
            'Transform your South African business with the most comprehensive CRM system that works 100% offline. Perfect for field sales teams, lead tracking, quotation management and employee monitoring.',
        images: [
            'https://storage.googleapis.com/crmapplications/resources/loro-twitter-image.jpg'
        ],
    },
    robots: {
        index: true,
        follow: true,
        nocache: false,
        googleBot: {
            index: true,
            follow: true,
            'max-image-preview': 'large',
            'max-snippet': -1,
            'max-video-preview': -1,
        },
    },
    alternates: {
        canonical: 'https://loro.co.za',
        languages: {
            'en-ZA': 'https://loro.co.za',
            'en-US': 'https://loro.com',
        },
    },
    category: 'Business Software',
    applicationName: 'LORO CRM',
    referrer: 'origin-when-cross-origin',
    creator: 'LORO CRM Team',
    publisher: 'LORO CRM',
    formatDetection: {
        telephone: true,
        address: true,
        email: true,
    },
    metadataBase: new URL('https://loro.co.za'),
    viewport: {
        width: 'device-width',
        initialScale: 1,
        maximumScale: 5,
    },
};

export default function LandingPageLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return children;
}
